/* GENERATED by scripts/gen-book-icons.mjs — do not edit by hand.
   Sources: Iconify's Lucide (interface icons) and Simple Icons (brand marks),
   both MIT licensed. Re-run the script to change the set. */

export interface BookIconNode { tag: string; attrs: Record<string, string> }
export interface BookIcon {
  name: string; label: string; viewBox: string; nodes: BookIconNode[];
  /** Elements > Icons sub-group. Absent on the social marks. */
  category?: string;
  /** Profile-URL template for a social mark; {h} is the cleaned handle. */
  url?: string;
  /** Simple Icons are solid shapes; Lucide are open strokes. Decides which
    * attribute the colour is written to. */
  filled?: boolean;
}

/** The Elements > Icons library. */
export const BOOK_ICONS: readonly BookIcon[] = [
  {
    "name": "check",
    "label": "Check",
    "category": "Marks",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M20 6L9 17l-5-5"
        }
      }
    ]
  },
  {
    "name": "circle-check",
    "label": "Check circle",
    "category": "Marks",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m16 9l-5.5 5.5L8 12"
        }
      }
    ]
  },
  {
    "name": "x",
    "label": "Cross",
    "category": "Marks",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M18 6L6 18M6 6l12 12"
        }
      }
    ]
  },
  {
    "name": "info",
    "label": "Info",
    "category": "Marks",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 16v-4m0-4h.01"
        }
      }
    ]
  },
  {
    "name": "circle-alert",
    "label": "Warning",
    "category": "Marks",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 8v4m0 4h.01"
        }
      }
    ]
  },
  {
    "name": "circle-help",
    "label": "Question",
    "category": "Marks",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3m.08 4h.01"
        }
      }
    ]
  },
  {
    "name": "star",
    "label": "Star",
    "category": "Marks",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.12 2.12 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.12 2.12 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.12 2.12 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.12 2.12 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.12 2.12 0 0 0 1.597-1.16z"
        }
      }
    ]
  },
  {
    "name": "heart",
    "label": "Heart",
    "category": "Marks",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M2 9.5a5.5 5.5 0 0 1 9.591-3.676a.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5"
        }
      }
    ]
  },
  {
    "name": "bookmark",
    "label": "Bookmark",
    "category": "Marks",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z"
        }
      }
    ]
  },
  {
    "name": "flag",
    "label": "Flag",
    "category": "Marks",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M4 22V4a1 1 0 0 1 .4-.8A6 6 0 0 1 8 2c3 0 5 2 7.333 2q2 0 3.067-.8A1 1 0 0 1 20 4v10a1 1 0 0 1-.4.8A6 6 0 0 1 16 16c-3 0-5-2-8-2a6 6 0 0 0-4 1.528"
        }
      }
    ]
  },
  {
    "name": "quote",
    "label": "Quote",
    "category": "Marks",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M16 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2a1 1 0 0 1 1 1v1a2 2 0 0 1-2 2a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1a6 6 0 0 0 6-6V5a2 2 0 0 0-2-2zM5 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2a1 1 0 0 1 1 1v1a2 2 0 0 1-2 2a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1a6 6 0 0 0 6-6V5a2 2 0 0 0-2-2z"
        }
      }
    ]
  },
  {
    "name": "thumbs-up",
    "label": "Thumbs up",
    "category": "Marks",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M15 5.88L14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88M7 10v12"
        }
      }
    ]
  },
  {
    "name": "briefcase",
    "label": "Briefcase",
    "category": "Business",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"
        }
      },
      {
        "tag": "rect",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "width": "20",
          "height": "14",
          "x": "2",
          "y": "6",
          "rx": "2"
        }
      }
    ]
  },
  {
    "name": "target",
    "label": "Target",
    "category": "Business",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      },
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "12",
          "r": "6"
        }
      },
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "12",
          "r": "2"
        }
      }
    ]
  },
  {
    "name": "trending-up",
    "label": "Trending up",
    "category": "Business",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M16 7h6v6"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m22 7l-8.5 8.5l-5-5L2 17"
        }
      }
    ]
  },
  {
    "name": "chart-column",
    "label": "Chart",
    "category": "Business",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M3 3v16a2 2 0 0 0 2 2h16m-3-4V9m-5 8V5M8 17v-3"
        }
      }
    ]
  },
  {
    "name": "lightbulb",
    "label": "Idea",
    "category": "Business",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M15 14c.2-1 .7-1.7 1.5-2.5c1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5c.7.7 1.3 1.5 1.5 2.5m0 4h6m-5 4h4"
        }
      }
    ]
  },
  {
    "name": "rocket",
    "label": "Rocket",
    "category": "Business",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M9 12a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.4 22.4 0 0 1-4 2z"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M9 12H4s.55-3.03 2-4c1.62-1.08 5 .05 5 .05"
        }
      }
    ]
  },
  {
    "name": "trophy",
    "label": "Trophy",
    "category": "Business",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M10 14.66V17a1 1 0 0 1-1 1a2 2 0 0 0-2 2v2m7-7.34V17a1 1 0 0 0 1 1a2 2 0 0 1 2 2v2m.916-12H19.5A2.5 2.5 0 0 0 22 7.5V5a1 1 0 0 0-1-1h-3M4 22h16"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M6 9a6 6 0 0 0 12 0V3a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1z"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M6.084 10H4.5A2.5 2.5 0 0 1 2 7.5V5a1 1 0 0 1 1-1h3"
        }
      }
    ]
  },
  {
    "name": "handshake",
    "label": "Handshake",
    "category": "Business",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m11 17l2 2a1 1 0 1 0 3-3"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m14 14l2.5 2.5a1 1 0 1 0 3-3l-3.88-3.88a3 3 0 0 0-4.24 0l-.88.88a1 1 0 1 1-3-3l2.81-2.81a5.79 5.79 0 0 1 7.06-.87l.47.28a2 2 0 0 0 1.42.25L21 4"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m21 3l1 11h-2M3 3L2 14l6.5 6.5a1 1 0 1 0 3-3M3 4h8"
        }
      }
    ]
  },
  {
    "name": "presentation",
    "label": "Presentation",
    "category": "Business",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M2 3h20m-1 0v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V3m4 18l5-5l5 5"
        }
      }
    ]
  },
  {
    "name": "zap",
    "label": "Energy",
    "category": "Business",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M15.914 4a1.5 1.5 0 0 0-2.474-1.561l-9 9A1.5 1.5 0 0 0 5.5 14h4.002a.5.5 0 0 1 .471.666L8.086 20a1.5 1.5 0 0 0 2.475 1.56l9-9A1.5 1.5 0 0 0 18.5 10h-3.997a.5.5 0 0 1-.472-.667z"
        }
      }
    ]
  },
  {
    "name": "shopping-cart",
    "label": "Cart",
    "category": "Money",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m2.05 2.05l1.099-.028a1 1 0 0 1 1.008.815l2.69 14.347A1 1 0 0 0 7.83 18H18"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M4.563 5h16.435a1 1 0 0 1 .981 1.204l-1.026 6.226A2 2 0 0 1 18.962 14H6.25"
        }
      },
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "18",
          "cy": "20",
          "r": "2"
        }
      },
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "8",
          "cy": "20",
          "r": "2"
        }
      }
    ]
  },
  {
    "name": "credit-card",
    "label": "Card",
    "category": "Money",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "rect",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "width": "20",
          "height": "14",
          "x": "2",
          "y": "5",
          "rx": "2"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M2 10h20M6 14h2"
        }
      }
    ]
  },
  {
    "name": "dollar-sign",
    "label": "Dollar",
    "category": "Money",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 2v20m5-17H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"
        }
      }
    ]
  },
  {
    "name": "tag",
    "label": "Tag",
    "category": "Money",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z"
        }
      },
      {
        "tag": "circle",
        "attrs": {
          "fill": "currentColor",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "7.5",
          "cy": "7.5",
          "r": ".5"
        }
      }
    ]
  },
  {
    "name": "gift",
    "label": "Gift",
    "category": "Money",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 7v14m8-10v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-8m3.5-4a1 1 0 0 1 0-5A4.8 8 0 0 1 12 7a4.8 8 0 0 1 4.5-5a1 1 0 0 1 0 5"
        }
      },
      {
        "tag": "rect",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "width": "18",
          "height": "4",
          "x": "3",
          "y": "7",
          "rx": "1"
        }
      }
    ]
  },
  {
    "name": "wallet",
    "label": "Wallet",
    "category": "Money",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4"
        }
      }
    ]
  },
  {
    "name": "piggy-bank",
    "label": "Savings",
    "category": "Money",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M11 17h3v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-3a3.16 3.16 0 0 0 2-2h1a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1h-1a5 5 0 0 0-2-4V3a4 4 0 0 0-3.2 1.6l-.3.4H11a6 6 0 0 0-6 6v1a5 5 0 0 0 2 4v3a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1zm5-7h.01M2 8v1a2 2 0 0 0 2 2h1"
        }
      }
    ]
  },
  {
    "name": "mail",
    "label": "Email",
    "category": "Contact",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m22 7l-8.991 5.727a2 2 0 0 1-2.009 0L2 7"
        }
      },
      {
        "tag": "rect",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "width": "20",
          "height": "16",
          "x": "2",
          "y": "4",
          "rx": "2"
        }
      }
    ]
  },
  {
    "name": "phone",
    "label": "Phone",
    "category": "Contact",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233a14 14 0 0 0 6.392 6.384"
        }
      }
    ]
  },
  {
    "name": "message-circle",
    "label": "Message",
    "category": "Contact",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092a10 10 0 1 0-4.777-4.719"
        }
      }
    ]
  },
  {
    "name": "send",
    "label": "Send",
    "category": "Contact",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11zm7.318-19.539l-10.94 10.939"
        }
      }
    ]
  },
  {
    "name": "at-sign",
    "label": "At sign",
    "category": "Contact",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "12",
          "r": "4"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-4 8"
        }
      }
    ]
  },
  {
    "name": "globe",
    "label": "Website",
    "category": "Contact",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 2a14.5 14.5 0 0 0 0 20a14.5 14.5 0 0 0 0-20M2 12h20"
        }
      }
    ]
  },
  {
    "name": "map-pin",
    "label": "Location",
    "category": "Contact",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0"
        }
      },
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "10",
          "r": "3"
        }
      }
    ]
  },
  {
    "name": "calendar",
    "label": "Calendar",
    "category": "Time",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M8 2v3m8-3v3"
        }
      },
      {
        "tag": "rect",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "width": "18",
          "height": "18",
          "x": "3",
          "y": "3",
          "rx": "2"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M3 9h18"
        }
      }
    ]
  },
  {
    "name": "clock",
    "label": "Clock",
    "category": "Time",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 6v6l4 2"
        }
      }
    ]
  },
  {
    "name": "timer",
    "label": "Timer",
    "category": "Time",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M10 2h4m-2 12l3-3"
        }
      },
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "14",
          "r": "8"
        }
      }
    ]
  },
  {
    "name": "hourglass",
    "label": "Hourglass",
    "category": "Time",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M5 22h14M5 2h14m-2 20v-4.172a2 2 0 0 0-.586-1.414L12 12l-4.414 4.414A2 2 0 0 0 7 17.828V22M7 2v4.172a2 2 0 0 0 .586 1.414L12 12l4.414-4.414A2 2 0 0 0 17 6.172V2"
        }
      }
    ]
  },
  {
    "name": "alarm-clock",
    "label": "Alarm",
    "category": "Time",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "13",
          "r": "8"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 9v4l2 2M5 3L2 6m20 0l-3-3M6.38 18.7L4 21m13.64-2.33L20 21"
        }
      }
    ]
  },
  {
    "name": "book-open",
    "label": "Book",
    "category": "Documents",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 5v16m8.001-2A2 2 0 0 0 22 17V5a2 2 0 0 0-1.999-2L16 3.002A5 5 0 0 0 12 5a5 5 0 0 0-4-2H4a2 2 0 0 0-2 2v12a2 2 0 0 0 1.999 2H8a5 5 0 0 1 4 2a5 5 0 0 1 4-2z"
        }
      }
    ]
  },
  {
    "name": "file-text",
    "label": "Document",
    "category": "Documents",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M14 2v5a1 1 0 0 0 1 1h5M10 9H8m8 4H8m8 4H8"
        }
      }
    ]
  },
  {
    "name": "folder",
    "label": "Folder",
    "category": "Documents",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"
        }
      }
    ]
  },
  {
    "name": "clipboard",
    "label": "Clipboard",
    "category": "Documents",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "rect",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "width": "8",
          "height": "4",
          "x": "8",
          "y": "2",
          "rx": "1",
          "ry": "1"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"
        }
      }
    ]
  },
  {
    "name": "notebook-pen",
    "label": "Notebook",
    "category": "Documents",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M13.4 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-7.4M2 6h4m-4 4h4m-4 4h4m-4 4h4"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M21.378 5.626a1 1 0 1 0-3.004-3.004l-5.01 5.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z"
        }
      }
    ]
  },
  {
    "name": "printer",
    "label": "Printer",
    "category": "Documents",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2M6 9V3a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v6"
        }
      },
      {
        "tag": "rect",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "width": "12",
          "height": "8",
          "x": "6",
          "y": "14",
          "rx": "1"
        }
      }
    ]
  },
  {
    "name": "paperclip",
    "label": "Attachment",
    "category": "Documents",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m16 6l-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551"
        }
      }
    ]
  },
  {
    "name": "user",
    "label": "Person",
    "category": "People",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"
        }
      },
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "7",
          "r": "4"
        }
      }
    ]
  },
  {
    "name": "users",
    "label": "Group",
    "category": "People",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M16 3.128a4 4 0 0 1 0 7.744M22 21v-2a4 4 0 0 0-3-3.87"
        }
      },
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "9",
          "cy": "7",
          "r": "4"
        }
      }
    ]
  },
  {
    "name": "user-plus",
    "label": "Add person",
    "category": "People",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"
        }
      },
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "9",
          "cy": "7",
          "r": "4"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M19 8v6m3-3h-6"
        }
      }
    ]
  },
  {
    "name": "graduation-cap",
    "label": "Student",
    "category": "People",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0zM22 10v6"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M6 12.5V16a6 3 0 0 0 12 0v-3.5"
        }
      }
    ]
  },
  {
    "name": "play",
    "label": "Play",
    "category": "Media",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z"
        }
      }
    ]
  },
  {
    "name": "camera",
    "label": "Camera",
    "category": "Media",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z"
        }
      },
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "13",
          "r": "3"
        }
      }
    ]
  },
  {
    "name": "image",
    "label": "Picture",
    "category": "Media",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "rect",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "width": "18",
          "height": "18",
          "x": "3",
          "y": "3",
          "rx": "2",
          "ry": "2"
        }
      },
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "9",
          "cy": "9",
          "r": "2"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m21 15l-3.086-3.086a2 2 0 0 0-2.828 0L6 21"
        }
      }
    ]
  },
  {
    "name": "music",
    "label": "Music",
    "category": "Media",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M9 18V5l12-2v13"
        }
      },
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "6",
          "cy": "18",
          "r": "3"
        }
      },
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "18",
          "cy": "16",
          "r": "3"
        }
      }
    ]
  },
  {
    "name": "video",
    "label": "Video",
    "category": "Media",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m16 13l5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5"
        }
      },
      {
        "tag": "rect",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "width": "14",
          "height": "12",
          "x": "2",
          "y": "6",
          "rx": "2"
        }
      }
    ]
  },
  {
    "name": "mic",
    "label": "Microphone",
    "category": "Media",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 19v3m7-12v2a7 7 0 0 1-14 0v-2"
        }
      },
      {
        "tag": "rect",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "width": "6",
          "height": "13",
          "x": "9",
          "y": "2",
          "rx": "3"
        }
      }
    ]
  },
  {
    "name": "headphones",
    "label": "Headphones",
    "category": "Media",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M3 14h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-7a9 9 0 0 1 18 0v7a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3"
        }
      }
    ]
  },
  {
    "name": "sun",
    "label": "Sun",
    "category": "Nature",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "12",
          "r": "4"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 2v2m0 16v2M4.93 4.93l1.41 1.41m11.32 11.32l1.41 1.41M2 12h2m16 0h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41"
        }
      }
    ]
  },
  {
    "name": "moon",
    "label": "Moon",
    "category": "Nature",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401"
        }
      }
    ]
  },
  {
    "name": "cloud",
    "label": "Cloud",
    "category": "Nature",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9"
        }
      }
    ]
  },
  {
    "name": "leaf",
    "label": "Leaf",
    "category": "Nature",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M11 20a10 10 0 0 0 10-10a25.9 25.9 0 0 0-1.04-7.281a1 1 0 0 0-1.755-.325C15.833 5.5 13 5.5 9.8 6.1A7 7 0 0 0 11 20"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M2 21a5 5 0 0 1 2.911-4.544C7.613 15.212 8.351 15.24 11 13"
        }
      }
    ]
  },
  {
    "name": "flame",
    "label": "Flame",
    "category": "Nature",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 3q1 4 4 6.5t3 5.5a1 1 0 0 1-14 0a5 5 0 0 1 1-3a1 1 0 0 0 5 0c0-2-1.5-3-1.5-5q0-2 2.5-4"
        }
      }
    ]
  },
  {
    "name": "droplet",
    "label": "Water",
    "category": "Nature",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 22a7 7 0 0 0 7-7c0-2-1-3.9-3-5.5s-3.5-4-4-6.5c-.5 2.5-2 4.9-4 6.5S5 13 5 15a7 7 0 0 0 7 7"
        }
      }
    ]
  },
  {
    "name": "settings",
    "label": "Settings",
    "category": "Tools",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M9.671 4.136a2.34 2.34 0 0 1 4.659 0a2.34 2.34 0 0 0 3.319 1.915a2.34 2.34 0 0 1 2.33 4.033a2.34 2.34 0 0 0 0 3.831a2.34 2.34 0 0 1-2.33 4.033a2.34 2.34 0 0 0-3.319 1.915a2.34 2.34 0 0 1-4.659 0a2.34 2.34 0 0 0-3.32-1.915a2.34 2.34 0 0 1-2.33-4.033a2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915"
        }
      },
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "12",
          "r": "3"
        }
      }
    ]
  },
  {
    "name": "wrench",
    "label": "Wrench",
    "category": "Tools",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-8.259 7.057l-7.91 7.91a1 1 0 0 1-2.999-3l7.91-7.91a6 6 0 0 1 7.057-8.259c.438.12.54.662.219.984z"
        }
      }
    ]
  },
  {
    "name": "key",
    "label": "Key",
    "category": "Tools",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m2 21l9.6-9.6m-4.1 4.1l2.3 2.3a1 1 0 0 1 0 1.4l-2.1 2.1a1 1 0 0 1-1.4 0L4 19"
        }
      },
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "15.5",
          "cy": "7.5",
          "r": "5.5"
        }
      }
    ]
  },
  {
    "name": "lock",
    "label": "Lock",
    "category": "Tools",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "rect",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "width": "18",
          "height": "11",
          "x": "3",
          "y": "11",
          "rx": "2",
          "ry": "2"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M7 11V7a5 5 0 0 1 10 0v4"
        }
      }
    ]
  },
  {
    "name": "search",
    "label": "Search",
    "category": "Tools",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m21 21l-4.34-4.34"
        }
      },
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "11",
          "cy": "11",
          "r": "8"
        }
      }
    ]
  },
  {
    "name": "pencil",
    "label": "Pencil",
    "category": "Tools",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497zM15 5l4 4"
        }
      }
    ]
  },
  {
    "name": "trash-2",
    "label": "Delete",
    "category": "Tools",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M10 11v6m4-6v6m5-11v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6M3 6h18M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"
        }
      }
    ]
  },
  {
    "name": "download",
    "label": "Download",
    "category": "Tools",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 15V3m9 12v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m7 10l5 5l5-5"
        }
      }
    ]
  },
  {
    "name": "upload",
    "label": "Upload",
    "category": "Tools",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 3v12m5-7l-5-5l-5 5m14 7v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"
        }
      }
    ]
  },
  {
    "name": "link",
    "label": "Link",
    "category": "Tools",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"
        }
      }
    ]
  },
  {
    "name": "external-link",
    "label": "External link",
    "category": "Tools",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M15 3h6v6m-11 5L21 3m-3 10v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"
        }
      }
    ]
  },
  {
    "name": "arrow-right",
    "label": "Arrow",
    "category": "Tools",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M5 12h14m-7-7l7 7l-7 7"
        }
      }
    ]
  },
  {
    "name": "house",
    "label": "Home",
    "category": "Tools",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"
        }
      }
    ]
  },
  {
    "name": "shield",
    "label": "Shield",
    "category": "Tools",
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"
        }
      }
    ]
  }
];

/** Brand marks and the two interface icons the social row offers. */
export const SOCIAL_ICONS: readonly BookIcon[] = [
  {
    "name": "brand:x",
    "label": "X",
    "url": "https://x.com/{h}",
    "filled": true,
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "currentColor",
          "d": "M14.234 10.162L22.977 0h-2.072l-7.591 8.824L7.251 0H.258l9.168 13.343L.258 24H2.33l8.016-9.318L16.749 24h6.993zm-2.837 3.299l-.929-1.329L3.076 1.56h3.182l5.965 8.532l.929 1.329l7.754 11.09h-3.182z"
        }
      }
    ]
  },
  {
    "name": "brand:instagram",
    "label": "Instagram",
    "url": "https://instagram.com/{h}",
    "filled": true,
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "currentColor",
          "d": "M7.03.084c-1.277.06-2.149.264-2.91.563a5.9 5.9 0 0 0-2.124 1.388a5.9 5.9 0 0 0-1.38 2.127C.321 4.926.12 5.8.064 7.076s-.069 1.688-.063 4.947s.021 3.667.083 4.947c.061 1.277.264 2.149.563 2.911c.308.789.72 1.457 1.388 2.123a5.9 5.9 0 0 0 2.129 1.38c.763.295 1.636.496 2.913.552c1.278.056 1.689.069 4.947.063s3.668-.021 4.947-.082c1.28-.06 2.147-.265 2.91-.563a5.9 5.9 0 0 0 2.123-1.388a5.9 5.9 0 0 0 1.38-2.129c.295-.763.496-1.636.551-2.912c.056-1.28.07-1.69.063-4.948c-.006-3.258-.02-3.667-.081-4.947c-.06-1.28-.264-2.148-.564-2.911a5.9 5.9 0 0 0-1.387-2.123a5.9 5.9 0 0 0-2.128-1.38c-.764-.294-1.636-.496-2.914-.55C15.647.009 15.236-.006 11.977 0S8.31.021 7.03.084m.14 21.693c-1.17-.05-1.805-.245-2.228-.408a3.7 3.7 0 0 1-1.382-.895a3.7 3.7 0 0 1-.9-1.378c-.165-.423-.363-1.058-.417-2.228c-.06-1.264-.072-1.644-.08-4.848c-.006-3.204.006-3.583.061-4.848c.05-1.169.246-1.805.408-2.228c.216-.561.477-.96.895-1.382a3.7 3.7 0 0 1 1.379-.9c.423-.165 1.057-.361 2.227-.417c1.265-.06 1.644-.072 4.848-.08c3.203-.006 3.583.006 4.85.062c1.168.05 1.804.244 2.227.408c.56.216.96.475 1.382.895s.681.817.9 1.378c.165.422.362 1.056.417 2.227c.06 1.265.074 1.645.08 4.848c.005 3.203-.006 3.583-.061 4.848c-.051 1.17-.245 1.805-.408 2.23c-.216.56-.477.96-.896 1.38a3.7 3.7 0 0 1-1.378.9c-.422.165-1.058.362-2.226.418c-1.266.06-1.645.072-4.85.079s-3.582-.006-4.848-.06m9.783-16.192a1.44 1.44 0 1 0 1.437-1.442a1.44 1.44 0 0 0-1.437 1.442M5.839 12.012a6.161 6.161 0 1 0 12.323-.024a6.162 6.162 0 0 0-12.323.024M8 12.008A4 4 0 1 1 12.008 16A4 4 0 0 1 8 12.008"
        }
      }
    ]
  },
  {
    "name": "brand:linkedin",
    "label": "LinkedIn",
    "url": "https://linkedin.com/in/{h}",
    "filled": true,
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "currentColor",
          "d": "M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037c-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85c3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.06 2.06 0 0 1-2.063-2.065a2.064 2.064 0 1 1 2.063 2.065m1.782 13.019H3.555V9h3.564zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0z"
        }
      }
    ]
  },
  {
    "name": "brand:facebook",
    "label": "Facebook",
    "url": "https://facebook.com/{h}",
    "filled": true,
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "currentColor",
          "d": "M9.101 23.691v-7.98H6.627v-3.667h2.474v-1.58c0-4.085 1.848-5.978 5.858-5.978c.401 0 .955.042 1.468.103a9 9 0 0 1 1.141.195v3.325a9 9 0 0 0-.653-.036a27 27 0 0 0-.733-.009c-.707 0-1.259.096-1.675.309a1.7 1.7 0 0 0-.679.622c-.258.42-.374.995-.374 1.752v1.297h3.919l-.386 2.103l-.287 1.564h-3.246v8.245C19.396 23.238 24 18.179 24 12.044c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.628 3.874 10.35 9.101 11.647"
        }
      }
    ]
  },
  {
    "name": "brand:youtube",
    "label": "YouTube",
    "url": "https://youtube.com/@{h}",
    "filled": true,
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "currentColor",
          "d": "M23.498 6.186a3.02 3.02 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.02 3.02 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.02 3.02 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.02 3.02 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814M9.545 15.568V8.432L15.818 12z"
        }
      }
    ]
  },
  {
    "name": "brand:tiktok",
    "label": "TikTok",
    "url": "https://tiktok.com/@{h}",
    "filled": true,
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "currentColor",
          "d": "M12.525.02c1.31-.02 2.61-.01 3.91-.02c.08 1.53.63 3.09 1.75 4.17c1.12 1.11 2.7 1.62 4.24 1.79v4.03c-1.44-.05-2.89-.35-4.2-.97c-.57-.26-1.1-.59-1.62-.93c-.01 2.92.01 5.84-.02 8.75c-.08 1.4-.54 2.79-1.35 3.94c-1.31 1.92-3.58 3.17-5.91 3.21c-1.43.08-2.86-.31-4.08-1.03c-2.02-1.19-3.44-3.37-3.65-5.71c-.02-.5-.03-1-.01-1.49c.18-1.9 1.12-3.72 2.58-4.96c1.66-1.44 3.98-2.13 6.15-1.72c.02 1.48-.04 2.96-.04 4.44c-.99-.32-2.15-.23-3.02.37c-.63.41-1.11 1.04-1.36 1.75c-.21.51-.15 1.07-.14 1.61c.24 1.64 1.82 3.02 3.5 2.87c1.12-.01 2.19-.66 2.77-1.61c.19-.33.4-.67.41-1.06c.1-1.79.06-3.57.07-5.36c.01-4.03-.01-8.05.02-12.07"
        }
      }
    ]
  },
  {
    "name": "brand:substack",
    "label": "Substack",
    "url": "https://{h}.substack.com",
    "filled": true,
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "currentColor",
          "d": "M22.539 8.242H1.46V5.406h21.08zM1.46 10.812V24L12 18.11L22.54 24V10.812zM22.54 0H1.46v2.836h21.08z"
        }
      }
    ]
  },
  {
    "name": "globe",
    "label": "Website",
    "url": "{h}",
    "filled": false,
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "circle",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      },
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 2a14.5 14.5 0 0 0 0 20a14.5 14.5 0 0 0 0-20M2 12h20"
        }
      }
    ]
  },
  {
    "name": "mail",
    "label": "Email",
    "url": "mailto:{h}",
    "filled": false,
    "viewBox": "0 0 24 24",
    "nodes": [
      {
        "tag": "path",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m22 7l-8.991 5.727a2 2 0 0 1-2.009 0L2 7"
        }
      },
      {
        "tag": "rect",
        "attrs": {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "width": "20",
          "height": "16",
          "x": "2",
          "y": "4",
          "rx": "2"
        }
      }
    ]
  }
];

/** The short list the Button inspector offers, in order. */
export const BUTTON_ICON_NAMES: readonly string[] = ["arrow-right","external-link","download","play","shopping-cart","mail","calendar","book-open"];

export const BOOK_ICONS_BY_NAME: Readonly<Record<string, BookIcon>> =
  Object.fromEntries([...BOOK_ICONS, ...SOCIAL_ICONS].map((i) => [i.name, i]));

export const BUTTON_ICONS: readonly BookIcon[] =
  BUTTON_ICON_NAMES.map((n) => BOOK_ICONS_BY_NAME[n]).filter(Boolean);

/* Lucide draws with stroke="currentColor" and Simple Icons fill with it.
   Resolving that to a literal hex rather than letting it inherit: currentColor
   is fine in browsers and modern EPUB readers, but Kindle's KF8 renderer is
   inconsistent with it, and an icon that silently falls back to black on a dark
   button is invisible. */
function resolved(icon: BookIcon, color: string): BookIconNode[] {
  return icon.nodes.map((n) => ({
    tag: n.tag,
    attrs: Object.fromEntries(Object.entries(n.attrs).map(([k, v]) => [k, v === "currentColor" ? color : v])),
  }));
}

/* Simple Icons ship no fill attribute at all — they are solid paths that inherit
   the text colour, so without this they paint black whatever the author picked. */
function paint(icon: BookIcon, nodes: BookIconNode[], color: string): BookIconNode[] {
  if (!icon.filled) return nodes;
  return nodes.map((n) => ({ ...n, attrs: { ...n.attrs, fill: color } }));
}

/** DOM-spec form, for a TipTap renderHTML output (what getHTML and the exports read). */
export function bookIconSpec(name: string, color: string, size = 16, cls = "book-btn-icon"): unknown[] | null {
  const icon = BOOK_ICONS_BY_NAME[name];
  if (!icon) return null;
  return ["svg", {
    class: cls, viewBox: icon.viewBox, width: String(size), height: String(size),
    "aria-hidden": "true", focusable: "false",
  }, ...paint(icon, resolved(icon, color), color).map((n) => [n.tag, n.attrs])];
}

/** String form, for a NodeView building its DOM by hand. */
export function bookIconHtml(name: string, color: string, size = 16, cls = "book-btn-icon"): string {
  const icon = BOOK_ICONS_BY_NAME[name];
  if (!icon) return "";
  const body = paint(icon, resolved(icon, color), color)
    .map((n) => "<" + n.tag + " " + Object.entries(n.attrs).map(([k, v]) => k + '="' + v + '"').join(" ") + "></" + n.tag + ">")
    .join("");
  return "<svg class=\"" + cls + "\" viewBox=\"" + icon.viewBox + "\" width=\"" + size + "\" height=\"" + size + "\" aria-hidden=\"true\" focusable=\"false\">" + body + "</svg>";
}

/* A handle arrives in every shape: @casper, casper, /casper, or a whole profile
   URL pasted out of the address bar. Reduce all of them to the bare handle, or
   the URL template doubles up — linkedin.com/in/<https://linkedin.com/in/casper>
   was the actual output before this took the last path segment. */
export function cleanHandle(raw: string): string {
  let h = (raw ?? "").trim();
  if (!h) return "";
  h = h.replace(/^https?:\/\//i, "").replace(/[?#].*$/, "").replace(/\/+$/, "");
  // A path means the handle is its last segment (linkedin.com/in/casper).
  if (h.includes("/")) h = h.split("/").filter(Boolean).pop() ?? "";
  // A bare host means a subdomain handle (casper.substack.com).
  else if (h.includes(".")) h = h.split(".")[0];
  return h.replace(/^@+/, "");
}

/** Profile URL for a social mark, or "" when there is nothing to point at. */
export function socialUrl(name: string, handle: string): string {
  const icon = BOOK_ICONS_BY_NAME[name];
  const raw = (handle ?? "").trim();
  if (!icon?.url || !raw) return "";
  /* Two templates take the value whole rather than as a handle. An address is
     not a path segment — cleanHandle would turn you@example.com into "you@example"
     — and a website is the entire URL by definition. */
  if (icon.url.startsWith("mailto:")) return "mailto:" + raw.replace(/^mailto:/i, "");
  if (icon.url === "{h}") return /^https?:\/\//i.test(raw) ? raw : "https://" + raw.replace(/^\/+/, "");
  const h = cleanHandle(raw);
  return h ? icon.url.replace("{h}", h) : "";
}
